source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target "Backbone-IOS-Demo" do
    #pod 'BackboneSwift', :git => "https://github.com/supersabbath/BackboneSwift3.0.git" ,  :branch => 'master'
    pod 'BackboneSwift' , :path => "/Users/canon/Projects/tempBackboneSwift/BackboneSwift"
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end
