# Uncomment the next line to define a global platform for your project
platform :tvos, '9.0'

target 'Backbone-tvOS-Demo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Backbone-tvOS-Demo
  pod 'BackboneSwift' , :path => "~/Proyectos/BackboneSwift3.0"
end
